language: ruby
rvm:
  - 2.3.3
  - 2.4.0
script: "bundle exec rake"
services:
  - redis-server
notifications:
  email:
    recipients:
      - dev-info@wanelo.com
      - kigster@gmail.com
    on_success: never
    on_failure: always
