language: ruby
rvm:
  - 2.3.3
  - 2.4.3
  - 2.5.0
script: "bundle exec rake || ( sleep 1; bundle exec rspec --only-failures ) "
services:
  - redis-server
notifications:
  email:
    recipients:
      - kigster@gmail.com
    on_success: never
    on_failure: always
